spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lavcraft/spring-boot-and-cloud-workshop-joker2017-configs.git
          repos:
            "*/remote": https://github.com/lavcraft/spring-boot-and-cloud-workshop-joker2017-configs.git
            "*/local": file:${HOME}/git/trainings/spring-boot-ripper-training/configs
  application:
    name: config-server

eureka:
 client:
  serviceUrl:
   defaultZone: ${EUREKA_SERV:http://127.0.0.1:8761/eureka/}

server:
  port: 8888
